
-- DATABASE TABLE CREATION SCRIPTS


-- 1. Create TARIFFS Table
CREATE TABLE TARIFFS (
    TARIFF_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    MONTHLY_FEE NUMBER(10, 2),
    DATA_LIMIT NUMBER,
    MINUTE_LIMIT NUMBER,
    SMS_LIMIT NUMBER
);

-- 2. Create CUSTOMERS Table
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    CITY VARCHAR2(100),
    SIGNUP_DATE DATE,
    TARIFF_ID NUMBER,
    CONSTRAINT fk_customer_tariff FOREIGN KEY (TARIFF_ID) REFERENCES TARIFFS(TARIFF_ID)
);

-- 3. Create MONTHLY_STATS Table
CREATE TABLE MONTHLY_STATS (
    STAT_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    DATA_USAGE NUMBER(10, 2),
    MINUTE_USAGE NUMBER(10, 2),
    SMS_USAGE NUMBER,
    PAYMENT_STATUS VARCHAR2(20),
    CONSTRAINT fk_stats_customer FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

-- 4. Create Indexes for Performance Optimization
CREATE INDEX idx_customers_city ON CUSTOMERS(CITY);
CREATE INDEX idx_customers_signup ON CUSTOMERS(SIGNUP_DATE);
CREATE INDEX idx_stats_payment ON MONTHLY_STATS(PAYMENT_STATUS);

COMMIT;
